### PR TITLE
Suggested update to README.md

### PR DESCRIPTION
**Pull request by iiilock3iii**
Suggested link for another regex tester website

### CODE REVIEW

**Comment by iiilock3iii** [comment]
Suggested link for another regex tester website

**Comment by iangilman** [comment]
Awesome, thank you! 

Out of curiosity, how did you find this repo? :)

**Comment by iiilock3iii** [comment]
One of my co-workers found it and posted it in one of our IM channels :)

**Comment by spacerockzero** [comment]
I had found it like a year ago and watched it. I found it in my "watched" list this am when i was looking for training content for our company's skills program, and I re-shared it on our company chat. @iiilock3iii is my coworker.
You have a great resource here!

**Comment by iangilman** [comment]
Awesome, good to hear!

**Pull request merged**
