### PR TITLE
Most critical feedback possible is appreciated for my first pull request!

### PR DESCRIPTION
**Pull request by ODRny**
I'm assuming this is where I explain the changes I've made. I'll list them in order from top to bottom listed in your main. If there is a clearer way to reference changes, please let me know!

- ### Deleted **Lesson/Challenges:** https://watchandcode.com/p/practical-javascript
"Not Found. The requested resource was not found on this server"
- ### Replaced **General:** How to get faster pull request reviews
"404, This is not the web page you are looking for." 
I have replaced it with another link that seems to hold the information this repo used to have, someone must have cloned it. I believe it's a Chinese-based version control website because it will ask to translate to English (at least on Google Chrome"
- ### Deleted **Code to Fiddle With:** http://www.ellipsetours.com/demos/
Blank page, website not secure, "404 - File or directory not found"
- ### Replaced **Code to Fiddle With** : https://github.com/openseadragon/openseadragon/issues
### labels=good+first+bug&page=1&state=open
"No results matched your search". I have suggested new search critirea. Instead of _is:open label:"good first bug"_ , I entered _bug label:"good first issue"_
- ### Deleted **Project Ideas:** http://ideasource.blankdots.com/
"This site can't be reached", probably discontinued
- ### Deleted **For Kids:**  Apps To Get Your Kids Coding On The iPad, Part 1/Apps To Get Your Kids Coding On The iPad, Part 2
"Invalid SSL certificate, Error code 526". I was able to open it on my phone browser. The sites are not secure. 
- ### Deleted **More Resource lists:** Resource list from JavaScript group on Facebook (https://www.facebook.com/notes/javascript/resources-for-learning-javascript/10151409218055343/)
Looks like it's been removed/discontinued. 
- ### Deleted **Finding Open Source Projects to Contribute to:** openhatch.org
I googled them, they are not requesting anymore contributions.

### CODE REVIEW

**Comment by evangrim** [comment]
There may or may not be valid critical feedback for you here, but I'm just here to say congrats on your first PR. Thanks for helping take care of this repo.

Best of luck!

**Comment by ODRny** [comment]
Thank you, that means a lot.

**Review by iangilman — CHANGES_REQUESTED** [review]
Wonderful! Thank you for going through and cleaning this up! I want to take a closer look, but I might not be able to get to it today. It looks good from what I've seen, though. Thank you for the thorough list of changes :-)

The one thing I know I'll want fixed is we don't need the README-update.md file… all we need are the changes to the original README.md.

I'll get back to you once I've had a chance to review more thoroughly!

**Review by iangilman — CHANGES_REQUESTED** [review]
OK, I've now had a chance to take a closer look. This is all great… I agree with all your edits. I appreciate you tracking down the alternate source for the pull request reviews piece, and figuring out the correct new search for the OpenSeadragon issues! Thank you as well for the thorough notes. 

The only thing that needs doing before this can be merged is removing the README-update.md file (since we don't need the duplicate in the repository). Please take care of that and let me know, and I will merge! :-)

**Review by iangilman — APPROVED** [review]
Fantastic! Thank you for helping to keep this list up-to-date!

**Pull request merged**
